### ISSUE TITLE
Heroku Link Error

### ISSUE THREAD

**Issue by DiptoChakrabarty** [JBossOutreach/certificate-generator-server-archive#70]
Heroku link provided in the repository description doesn't seem to be working 
![Screenshot from 2020-07-23 14-18-19](https://user-images.githubusercontent.com/45638240/88268035-63b0c280-ccef-11ea-8238-b7412b863cbd.png)

**Comment by aashutoshrathi** [comment]
Hi,
Please refer to this file `https://github.com/JBossOutreach/certificate-generator-server-archive/blob/master/api/urls.py`
Append `/api/<module>`
For eg: https://cert-gen-jboss.herokuapp.com/api/org/
Thanks
